export interface UserModel{
    id: string; //I changed from number to string because it get error(Argument of type 'number' is not assignable to parameter of type 
    // 'string'.) in login.component.ts return of data.id which is a string generated by mongodb atlas.
    username: string;
    password: string;
    log: object;
}